# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/unites.ui'
#
# Created: Wed Dec 11 11:03:52 2013
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(597, 501)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtGui.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.unites = QtGui.QTreeView(self.groupBox)
        self.unites.setObjectName("unites")
        self.horizontalLayout.addWidget(self.unites)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -70, 255, 520))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.proprietes = QtGui.QTableView(self.scrollAreaWidgetContents)
        self.proprietes.setMinimumSize(QtCore.QSize(0, 250))
        self.proprietes.setObjectName("proprietes")
        self.verticalLayout.addWidget(self.proprietes)
        self.coutEnable = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.coutEnable.setTristate(False)
        self.coutEnable.setObjectName("coutEnable")
        self.verticalLayout.addWidget(self.coutEnable)
        self.couts = QtGui.QTableView(self.scrollAreaWidgetContents)
        self.couts.setEnabled(True)
        self.couts.setObjectName("couts")
        self.verticalLayout.addWidget(self.couts)
        self.produitEnable = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.produitEnable.setObjectName("produitEnable")
        self.verticalLayout.addWidget(self.produitEnable)
        self.produit = QtGui.QTableView(self.scrollAreaWidgetContents)
        self.produit.setObjectName("produit")
        self.verticalLayout.addWidget(self.produit)
        self.ameliorationEnable = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.ameliorationEnable.setObjectName("ameliorationEnable")
        self.verticalLayout.addWidget(self.ameliorationEnable)
        self.amelioration = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.amelioration.setObjectName("amelioration")
        self.verticalLayout.addWidget(self.amelioration)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.coutEnable, QtCore.SIGNAL("toggled(bool)"), self.couts.setVisible)
        QtCore.QObject.connect(self.produitEnable, QtCore.SIGNAL("toggled(bool)"), self.produit.setVisible)
        QtCore.QObject.connect(self.ameliorationEnable, QtCore.SIGNAL("toggled(bool)"), self.amelioration.setVisible)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Unités", None, QtGui.QApplication.UnicodeUTF8))
        self.coutEnable.setText(QtGui.QApplication.translate("Form", "Coûts", None, QtGui.QApplication.UnicodeUTF8))
        self.produitEnable.setText(QtGui.QApplication.translate("Form", "Produit", None, QtGui.QApplication.UnicodeUTF8))
        self.ameliorationEnable.setText(QtGui.QApplication.translate("Form", "S\'améliore", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Général", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Construit", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Nécessite", None, QtGui.QApplication.UnicodeUTF8))

